development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: enovic_dev
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432
  template: template0